language: bash
before-install:
  - git clone --depth=50 --branch=master https://github.com/alexzhangs/xsh.git alexzhangs/xsh
  - bash alexzhangs/xsh/install.sh
install:
  - source ~/.bash_profile
  - xsh load -b "$TRAVIS_BRANCH" xsh-lib/core
script:
  - xsh list
  - bash test.sh
